title: lightalytics
author: Rod Light
email: rod.light@lightalytics.com
description: >
  lightalytics
linkedin_username: lightalytics
google_analytics: "UA-93077459-1"
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE*
  - Makefile
baseurl: ""
